# Cloud container builder pipeline for building all docker images for the the Java Runtime Builder.
# https://cloud.google.com/container-builder/docs/overview

steps:
# Build the maven project, omitting the docker build step
- name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
  args: ['-B', '-P-local-docker-build', 'clean', 'install']
  id: 'MAVEN'

# Execute the docker build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=${_IMAGE}', '--no-cache', 'java-runtime-builder-docker/target/classes/docker']
  id: 'DOCKER'

# Runtimes-common structure tests
# See https://github.com/GoogleCloudPlatform/runtimes-common/tree/master/structure_tests
- name: 'gcr.io/gcp-runtimes/structure_test'
  args: ['--image', '${_IMAGE}', '-v', '--config', '/workspace/test/structure/structure.yaml']
  id: 'STRUCTURE_TEST'

images: ['${_IMAGE}']
