# TODO java_binary build rule for the entire application
java_binary(
    name = "java-runtime-builder",
    srcs = glob(["**/*.java"]),
    deps = [
        #        "@com_google_guava_guava//jar",
        #        "@com_google_inject_guice//jar",
        #        "@org_apache_maven_shared_maven_invoker//jar",
        #        "@org_slf4j_slf4j_api//jar",
        #        "//src/main/java/com/google/cloud/runtimes/builder/buildsteps/base:build_step_base",
    ],
)
